### ISSUE TITLE
Fix invalid authToken

### ISSUE THREAD

**Issue by Sigri44** [ImoucheG/GeoRide-Jeedom-Source#10]
Hello,

Je vois qu'après un certain temps, le Bearer token expire, et donc le plugin crash.
La fonction pour générer le Bearer existe déjà dans la config, ne serait il pas possible de relancer la fonction (à l'aide des credentials déjà remplis), afin de générer un nouveau token ?

Je suis en train de tester voir si j'arriverais à gérer l'intégration, dans ce cas je ferais une PR

Sigri

**Comment by ImoucheG** [comment]
Salut,

En effet, c'était une de mes décisions il y a longtemps de ne pas sauvegarder les credentials, seul le token est sauvegardé après génération. Tu n'es pas le premier à faire la demande :) 

Je vais voir ce que je peux faire sans de GeoRide sous la main !

**Comment by daodevinc** [comment]
> Salut,
> 
> En effet, c'était une de mes décisions il y a longtemps de ne pas sauvegarder les credentials, seul le token est sauvegardé après génération. Tu n'es pas le premier à faire la demande :)
> 
> Je vais voir ce que je peux faire sans de GeoRide sous la main !

Hésites pas si besoin, j'avoue que c'est moins pratique de devoir régulièrement resave.

**Comment by ImoucheG** [comment]
Salut, 

J'ai commencé les modifications, les credentials pour récupérer le token sont gardés.
Néanmoins, je me penché sur un daily pour regen le token mais GeoRide à ban min IP ou l'user agent de mon Jeedom ^^"
```
TooManyRequests
```

Si tu as des pistes sur le TODO de la nouvelle branche 89dcf05c77d5189184e196dec17bbb99f04f9c7d je suis prenneur le temps que je passe en whitelist, j'espère automatiquement !

https://github.com/ImoucheG/GeoRide-Jeedom-Source/blob/token-life/core/class/georide.class.php

```php
public function generateToken()
    {
        log::add(__CLASS__, 'error', 'Regénération du token');
        $ch = curl_init("https://api.georide.com/user/new-token");
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array('Authorization: Bearer ' . config::byKey('APIToken', 'georide')));
        $data = curl_exec($ch);
        curl_close($ch);
        // TODO: set response to replace token in config::byKey('APIToken', 'georide')
        // Warning: after many test georide api return "TooManyRequests" !
        // log::add(__CLASS__, 'error', 'TEST: ' . $data);
    }
```

![image](https://github.com/ImoucheG/GeoRide-Jeedom-Source/assets/9254052/82b6ae09-6e42-4db5-8fdb-472c4bbfc8bc)

**Comment by Sigri44** [comment]
https://github.com/ImoucheG/GeoRide-Jeedom-Source/pull/12
