### ISSUE TITLE
Hello c'est encore moi

### ISSUE THREAD

**Issue by sly83910** [ImoucheG/GeoRide-Jeedom-Source#2]
Salut,
On s'était eu il y a quelques temps car je ne parvenais pas à récupérer la position dynamique dans le Plugin Geoloc.
Là, mon Jeedom est chez moi, j'y accède bien depuis l'extérieur en HTTP 
Dans le plugin Georide, j'ai bien toutes mes infos, latitude longitude et tout
J'ai récupéré l'URL dans le plugin Geoloc : http://xxx.xxx.xxx.xxx:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=207&value=%LOCN
Que j'ai collé dans le plugin Georide mais lorsque je test la commande je n'ai rien 
![image](https://user-images.githubusercontent.com/61941483/77859359-33598b80-7209-11ea-8f1b-e69f1a98735d.png)

As tu des idées ? 

Merci pour ton Aide

Sylvain

**Comment by ImoucheG** [comment]
Salut,

As-tu configuré ton GeoLoc de la manière suivante :

![Capture](https://user-images.githubusercontent.com/9254052/77884417-4e59e900-7265-11ea-92cc-482918237560.JPG)


La commande 700 est en fixe et représente la localisation référentielle fixe (ex: maison), elle s'exprime en longitude,latitude (à entrer à la main dans le champ de droite) de mémoire, regarde la documentation de GeoLoc ;)

La commande 701 représente ta moto et à mettre en dynamique. Cette ce numéro de commande qui est à insérer dans l'ID de ton url GeoLoc. (Quand tu le créer il peut prendre un moment à actualiser ses informations).

La commande 702 calcul la distance entre ton référentielle et ta moto :) C'est elle qui te renvoie les informations utile. Tu peux mettre l'objet Géoloc sur ton dashboard pour avoir une mini map :).

Bien sûr les numéros de commandes seront différents chez toi.

Cordialement,

**Comment by sly83910** [comment]
Salut,

Oui j'ai renseigner les coordonnées GPS de chez moi.
Lorsque toi tu fais Tester sur ton 701, est ce qu'il t'affiche des valeurs
en haut en résultat?

Merci

**Comment by sly83910** [comment]
Je ne suis pas pro mais j'ai l'impression vu tes screens que tu est en V3.
Est ce le cas ?

Merci


Le lun. 30 mars 2020 à 09:13, Sylvain Blondet <blondet.sylvain@gmail.com> a
écrit :

**Comment by ImoucheG** [comment]
Je regarderais quand je serais rentré :)
En effet, je suis en V3, j'ai corrigé la compatibilité de GeoRide avec la V4, mais en effet, l'association GeoRide - GeoLoc peut poser problème.
Je ferais une VM pour test quand j'aurais un peu de temps.

Si tu prend ton URL de GeoLoc et que tu remplace ton %LOCN par des coordonnées GPS fictives (voir documentation GeoLoc, je ne me rappelle plus du format). Est-ce ta commande dynamique est renseignée ?

Tu peux utiliser ton navigateur ou POSTMAN de mémoire c'est une requête GET.
Cordialement,

**Comment by sly83910** [comment]
Voici ce que j'obtiens

[image: image.png]

**Comment by ImoucheG** [comment]
Je ne vois pas l'image :s
Ma commande 701 me renvoie la dernière valeur que GeoRide à envoyé par l'URL.

**Comment by sly83910** [comment]
Moi elle ne me renvoie rien et du coup la diff Maison-Georide non plus.
J'arrive pas à comprendre ou sa bèche et le plus frustrant c'est que dans
mon Plugin Georide j'ai bien mes coordonnées Latitude et Logitude ...

**Comment by sly83910** [comment]
Le screen que tu ne vois pas

https://drive.google.com/open?id=1U6E0ACaznNCF326WXXBv3hIzvYitG3vF


Le lun. 30 mars 2020 à 15:06, Sylvain Blondet <blondet.sylvain@gmail.com> a
écrit :

**Comment by ImoucheG** [comment]
Merci,
![image](https://user-images.githubusercontent.com/9254052/77916034-bece2d80-7298-11ea-8d98-c488530dc77e.png)
id est un numéro dans mon cas c'est 701 soit id=701 dans l'url.

NB: Pense à retirer ton screen, car tes messages sont en public sur GitHub ^^"
https://github.com/ImoucheG/GeoRide-Jeedom-Source/issues/2

**Comment by ImoucheG** [comment]
Dans la configuration du plugin GeoRide pense à activer un CRON pour qu'il envoie ta positions régulièrement.
![image](https://user-images.githubusercontent.com/9254052/77916594-9561d180-7299-11ea-8a8c-54a342913eba.png)

**Comment by sly83910** [comment]
Voila ce que j'ai

[image: image.png]

**Comment by ImoucheG** [comment]
Désolé ... j'ai toujours :
![image](https://user-images.githubusercontent.com/9254052/77917322-b8d94c00-729a-11ea-802a-171dd21fffc9.png)

**Comment by sly83910** [comment]
Désolé

https://drive.google.com/open?id=1zlz1qzlZQ9JEtYkhBsKxru3B5_gEv2iK

**Comment by ImoucheG** [comment]
Okay as-tu pu faire ta requête postman ?

![image](https://user-images.githubusercontent.com/9254052/77918657-7c0e5480-729c-11ea-8a40-bdceb132b71f.png)

Si tu ne reçois pas de réponse 200 c'est que tu as un problème d'accès au plug-in GeoLoc (je ne suis pas le développeur ^^"). Dans ce cas, je ne peux pas beaucoup t'aider plus à part te conseiller de vérifier ton firewall et routage. Il est possible que GeoLoc ne soit pas encore en Jeedom V4, je n'ai pas l'information en main.

**Comment by sly83910** [comment]
J'ai fait la requête en mettant une latitude longitude à la place du %LOCN
et ca me donne : Could not get any response

**Comment by ImoucheG** [comment]
Peut-tu me montrer l'url utilisé stp
NB: Tu peux cacher ton apikey, IP et mettre une coordonnée GPS fictive si tu veux :) Je n'ai besoin que de voir le format de ton url.

**Comment by sly83910** [comment]
http://83.113.235.187:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=[Garage][Position
Moto][Georide]&value=%LOCN

**Comment by sly83910** [comment]
Et j'ai mis des valeurs au pif près de chez moi
http://83.113.235.187:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=[Garage][Position
Moto][Georide]&value=43.653748,5.493408

Le lun. 30 mars 2020 à 15:58, Sylvain Blondet <blondet.sylvain@gmail.com> a
écrit :

**Comment by ImoucheG** [comment]
http://83.113.235.187:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=[Garage][Position
Moto][Georide]&value=43.653748,5.493408

Dans ton URL on peut voir que ton id est égale à "id=[Garage][Position
Moto][Georide]"

Ce n'est pas une bonne valeur, tu doit mettre le numéro de la commande dynamique (ta moto).
Dans mon cas, ma commande dynamique de GeoLoc est  :
![image](https://user-images.githubusercontent.com/9254052/77921519-276cd880-72a0-11ea-93b4-bac6241b2e5b.png)

Soit un numéro de commande 701.

Donc dans mon url je doit avoir comme id ==> ""id=701"

Soit une url complète comme ci-dessous :

http://83.113.235.187:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=701&value=43.653748,5.493408

Remplace bien sûr 701 par le numéro de ta commande propre à ton GeoLoc :)

**Comment by ImoucheG** [comment]
http://83.113.235.187:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=207&value=43.653748,5.493408

Je me suis permis de te requêter, l'url ci-dessus fonctionne (réponse 200), ta commande dynamique sur GeoLoc devrait avoir une valeur.

Cordialement,

**Comment by sly83910** [comment]
Alors j'avais bien mis cela et dans doute j'avais essayé en mettant avant
apres les # et en faisant ca, ca ma remplacé par "
[Garage][PositionMoto][Georide]" donc je pensais être dans le vrai.
J'ai remis mon id sans les "#" et pareil lorsque je teste c'est vide

**Comment by sly83910** [comment]
Yess j'ai des infos : qu'a tu fais, qu'est ce que j'ai loupé ???
Trop fort


Le lun. 30 mars 2020 à 16:17, Sylvain Blondet <blondet.sylvain@gmail.com> a
écrit :

**Comment by sly83910** [comment]
Mais la c'est avec les infos aléatoires que j'ai pris près de chez moi
Comment faire pour que se soit les infos de mon Georide?


Le lun. 30 mars 2020 à 16:19, Sylvain Blondet <blondet.sylvain@gmail.com> a
écrit :

**Comment by ImoucheG** [comment]
http://83.113.235.187:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=207&value=43.653748,5.493408

J'ai utilisé cette URL pour t'envoyer l'information, tu t'imagine bien qu'il faudra tu change ton APIKEY pour éviter des gens taquins t'envoie perpétuellement des trucs ^^" . Je ne sais pas comment en changer par contre, désolé ...

Donc maintenant dans GeoRide sur ta moto entre l'URL suivante tel quel sans rien changer :


http://83.113.235.187:80/plugins/geoloc/core/api/jeeGeoloc.php?apikey=RAAhD04Vmq9Ic294xxtRWyOl0pDs7LL4&id=207&value=%LOCN

Comme le screen ci-dessous:

![image](https://user-images.githubusercontent.com/9254052/77923781-32753800-72a3-11ea-8cd4-0b9cab2d5d5e.png)


Enregistre et attend 5 - 10 min pour voir si l'information se met à jour :)

**Comment by sly83910** [comment]
Je viens de comparer c'est bien ce que j'ai dans le champ.
Je vais attendre et rechecker.
Si ma commande 207 ne donne rien comme résultat, que dois je tester?J'ai
une regle pour rediriger le port 80 vers mon Jeedom, faut t-il en faire une
autre?
Le parefeu de ma livebox est en moyen, faut-il que je crée une règle?

Merci pour ton aide

**Comment by ImoucheG** [comment]
Vérifie bien car le moindre changement dans l'url (virgule, minuscule/majuscule, espace, ...) va foirer la requête ^^

Ta commande 207 donnera pour le moment toujours la dernière valeur acquise soit celle que je t'ai envoyé auparavant.

Si j'arrive à te requêter normalement tu as rien à changer, sauf si ton jeedom n'arrive pas  à s'attaquer lui même depuis une url externe.
En gros, si ton jeedom en intranet est en 192.168.1.2 par exemple, il est possible qu'il n'arrive pas à attaquer le http://83.113.235.187:80 pour se redirigé vers lui ensuite.
Pour tester essaie des traceroute (à faire depuis ta machine jeedom), ping etc
Tu trouvera des tuto sur le net je pense pour tester.

Pour le parfeu etc c'est une question de sécurité pour toi, car tes adresses IP etc se retrouve en public sur github à toi de voir :)

Cordialement,

**Comment by sly83910** [comment]
Effectivement j'ai la dernière valeur que tu as envoyé
Si sur mon navigateur je n'arrive pas à atteindre le Jeedom avec l'IP
publique, c'est peux être pour cela que sa ne fonctionne pas.
Je ne peux pas mettre mon ip locale au lieu de mon IP publique?

**Comment by sly83910** [comment]
Bingo j'ai remplacer 83.113.235.187:80 par l'IP locale de mon Jeedom et
j'ai la bonne valeur !!!!
Du coup quel intérêt d'allez mettre l'IP Publique??


Le lun. 30 mars 2020 à 16:47, Sylvain Blondet <blondet.sylvain@gmail.com> a
écrit :

**Comment by ImoucheG** [comment]
Mon jeedom est ouvert, donc je n'ai pas réfléchis à la question je t'avoue mais en effet, en terme de perf et sécurité c'est mieux ^^"
J'aurais appris quelques choses ahah

Cordialement,

**Comment by sly83910** [comment]
Si tu veux rajouter dans la docs pour que des newbie comme moi t'embête pas
^^
Tu n'as pas un Paypal pour te remercier du support?

**Comment by ImoucheG** [comment]
Yes tu m'a beaucoup aidé, j'ai plein de trucs à rajouter au wiki :)  Merci

https://www.paypal.me/imoucheg

Mais ne t'inquiète pas pour ça ! C'était avec plaisir :) En plus ça me fait des retours sur mon dev et documentation ! C'est déjà beaucoup :)

**Comment by sly83910** [comment]
Avec plaisir !!

Bordel au moment ou je test les serveurs de Georide en rade mdrrrr faut le
vivre !!

**Comment by ImoucheG** [comment]
Merci !! Il en fallait pas :) 

Oui pareil chez moi, ainsi que mes boites mails chez OVH par ailleurs !
