### ISSUE TITLE
Plus aucune infos depuis ce weekend

### ISSUE THREAD

**Issue by sly83910** [ImoucheG/GeoRide-Jeedom-Source#3]
Salut Guillaume,

Depuis ce weekend je n'ai plus rien qui remonte dans mon plugin Georide.
![image](https://user-images.githubusercontent.com/61941483/78538335-1b799d00-77f1-11ea-83e0-e485cf234093.png)
J'ai essayer de regénérer la clé API avec mon mail et mon MDP, a priori rien na changé
Tu as des infos?

Merci

**Comment by sly83910** [comment]
Laisse tomber je viens de retesté et j'ai bien les infos.
Je ne sais pas ce qu’il s'est passé.

A plus

**Comment by ImoucheG** [comment]
Salut,
Quand tu régénère une API Token pense à faire un F5 avant d'aller toucher à ton tracker.
GeoRide révoque régulièrement les token, une régénération est nécessaire à ce moment là.
Cordialement
:)

**Comment by sly83910** [comment]
Merci pour l'info ;)
