### ISSUE TITLE
Actualisation

### ISSUE THREAD

**Issue by sly83910** [ImoucheG/GeoRide-Jeedom-Source#4]
Salut,

J'avais une question sur le plugin.

Je me sert de la position de la moto pour Ouvrir par scénario la porte de mon garage.
Hors souvent j'arrive devant le garage et la porte n'est pas ouverte ou ne s'ouvre pas.

Je me suis rendu compte que l'actualisation de la position ne se fait que toutes les minutes.

Est-il possible de modifier cela afin que les intervalles soit plus courts ?
Pour éviter les requêtes frénétiques, est-il possible de réduire l'intervalle pendant une période donnée ( créneau approximatif de mon retour à la maison )?

Dans l'attente de te lire. 

bonne soirée

**Comment by ImoucheG** [comment]
Salut,

Pour que ce soit le top, je dois intégrer du socket.io mais sous PHP et adapter à Jeedom. Afin d'avoir les informations en "live".
En ce moment je suis un peu occupé, c'est sur ma TODO-LIST :)

Néanmoins, pour te dépanner (bricolage !) tu peux créer un scénario lancé à l'heure voulu :

![image](https://user-images.githubusercontent.com/9254052/99281992-6f426f00-2833-11eb-8d2d-035ff06cc11f.png)

Celui-ci, tourne tous les 5 secondes pendant une heure. Tu peux changer les variables à ta convenance.

Cordialement

**Comment by sly83910** [comment]
Top je vais tester cela !!!

Sylvain Blondet

**Comment by sly83910** [comment]
Hello,

Je voulais te demandais si ca faisait pareil chez toi:

J'ai créé ton scénario et lorsque je vais voir dans Analyse > Temps réel
j'ai les infos qui remontent toutes les minutes mais le reste du temps j'ai
cela :

[2020-11-17 18:55:28][INFO] : Exécution de la commande
[Garage][Georide][Refresh] avec les paramètres {"background":"0"}
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Locked] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Longitude] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Latitude] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Last location time] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Tracker name] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Button action] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Vibration level] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Role] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Last payment] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Odometer] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Stolen] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Crashed] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Speed] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Moving] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande
[Garage][Georide][Online] valeur :
[2020-11-17 18:55:29][INFO] : Evènement sur la commande [Garage][Position
Moto][Georide] valeur : , (répétition)

Comme ci l'API Georide filait les infos qu'un fois par minutes

Tu aurait une idée

Merci beaucoup




Le lun. 16 nov. 2020 à 18:03, Sylvain Blondet <blondet.sylvain@gmail.com> a
écrit :

> Top je vais tester cela !!!
>
> Sylvain Blondet
>

**Comment by ImoucheG** [comment]
Salut,

Dans le doute, relance ta génération de token:

![image](https://user-images.githubusercontent.com/9254052/99445819-64183d80-291e-11eb-80b1-127ffa3865ff.png)

Ainsi que les paramètres de geoloc url, si tu l'utilise:
![image](https://user-images.githubusercontent.com/9254052/99445939-8c07a100-291e-11eb-9a98-3538e3a336d4.png)
Vérifie si l'url n'as pas changé avec les mises à jours de GeoLoc, également que ton domaine/ip est toujours correcte et enfin si l'ID de la commande passé dans l'URL est toujours viable.
Si le problème persiste, essaie avec le champ URL vide pour voir s'il est bloquant ou pas.


Cordialement

**Comment by sly83910** [comment]
Je vais regarder je te tiens au courant!
Merci

Sylvain Blondet
