### ISSUE TITLE
Erreur API

### ISSUE THREAD

**Issue by Sigri44** [ImoucheG/GeoRide-Jeedom-Source#5]
Bonjour,

visiblement l'API a changé et ne semble plus faire fonctionner le plugin ?

Test de renseigner à nouveau de renseigner les login/password, sauvagarde, génération d'un nouveau token OK, F5 ok.

Dans la page du plugin, si on veut actualiser la liste des boitier/trackers, erreur :
![image](https://user-images.githubusercontent.com/9304947/123545883-b2b27380-d75a-11eb-821a-41fa159f0b44.png)

Merci

**Comment by ImoucheG** [comment]
Salut,

C'est possible avec l'arrivée de la V3. Mon V1 est malheureusement mort, je vais analyser le problème dans la mesure du possible :)

**Comment by ImoucheG** [comment]
Je viens d'essayer directement depuis le plug-in, mon token est bien récupéré.

Et la liste s'actualise également:
![image](https://user-images.githubusercontent.com/9254052/123602844-7e41c480-d7f9-11eb-810c-38dc5923dcd1.png)

1 - Peut-tu te connecter directement au site de GeoRide https://georide.fr/mon-compte/ avec les même logins ?
2 - As-tu accès depuis le même réseau de ton Jeedom à https://api.georide.fr/ ?
3 - Si tu as quelques notions pourrais-tu essayer user manuellement l'API  de GeoRide via "Postman" par exemple ?
Notamment sur les services suivants :  https://api.georide.fr/#api-User-LoginUser        ET        https://api.georide.fr/#api-User-UserTrackers
4 - Pourrais-tu me spécifier la version de ton Jeedom ?

Il est tout simplement possible que l'API était down ^^"

Cordialement :)

**Comment by daodevinc** [comment]
Hello,

Effectivement l'API était down car via Postman KO également.
Il y'aurait il moyen de faire une MaJ afin de proposer les params du GR 3 ? (batterie du boitier et de la moto)
Je peux faire une MR au besoin.

Merci

**Comment by ImoucheG** [comment]
Yes, je viens de voir les différentes modifications, je fais un test prochainement de ton MR (#6 ) afin de la valider.

Merci de ta participation ;)
