### ISSUE TITLE
Georide 3 : Unlock and Lock don't work

### ISSUE THREAD

**Issue by JPI1308** [ImoucheG/GeoRide-Jeedom-Source#7]
Hi,

Just get a GR3. I tried to use unlock and lock functionalities from Dashboard (and command test), it doesn't work, no status updated.

**Comment by ImoucheG** [comment]
Hi, 

I try it a moment ago, but my GeoRide is broken and the response of GeoRide API is "204 No content", perhaps he can't discuss with my tracker.
Can you test your tracker with his API, for check if the plugin or the API has a bug.

1 - https://api.georide.fr/#api-User-LoginUser
2 - https://api.georide.fr/#api-User-UserTrackers
3 - https://api.georide.fr/#api-Tracker-LockTracker
4 - https://api.georide.fr/#api-Tracker-UnlockTracker

You can use a software like Postman or other.

If the response is different of "200", the API is probably in cause. And we must have wait ...

NB: Before the steps can you regenerate a API Key from the configuration on Jeedom ? 
![image](https://user-images.githubusercontent.com/9254052/127448677-de63c595-6eb9-468f-b06f-3f48278ba821.png)

"CTRL+ F5" and relaunch the command (lock/unlock)

Cordially

**Comment by JPI1308** [comment]
Hi,

I have a GeoRide 3 for information. Maybe that’s the reason

Envoyé de mon iPhone

**Comment by JPI1308** [comment]
I will try and let you know

Envoyé de mon iPhone

**Comment by ImoucheG** [comment]
Ok, in this issue [https://github.com/ImoucheG/GeoRide-Jeedom-Source/issues/5](https://github.com/ImoucheG/GeoRide-Jeedom-Source/issues/5) the contributor has a GeoRide 3 and the plugin work.

**Comment by JPI1308** [comment]
Everything works except unlock and lock functionality. I will test 

Envoyé de mon iPhone

**Comment by JPI1308** [comment]
I tried with postman.
All Get call are ok for me. All Post calls are ko. I've got an 404 error
... with same Key that I use for Get request

**Comment by ImoucheG** [comment]
Hum ... 404 is weird. Do you have 404 with:

![image](https://user-images.githubusercontent.com/9254052/127467598-448746bc-c6ef-430c-a5ce-5a1c18faa43c.png)

In my case I have a 
![image](https://user-images.githubusercontent.com/9254052/127467711-afb7832b-d4bf-4141-9cb0-9db66c557f1c.png), so the API give me a response on this route. I have try to pass invalid TOKEN and/or invalid tracker ID. I cannot reproduce your 404 error.

But if you have "404", only on POST Method, GeoRide API or your network has a trouble I think. (firewall ?)

**Comment by JPI1308** [comment]
Pareil (on peut parler français) :-(
Mes requêtes en GET passent sans problème (j'ai testé en enlevant le token,
c'est KO, en le remettant c'est OK), ceci m'a permis de valider le token.
Les requetes en post sont toutes KO depuis postman (alors que je n'ai pas
de statut d'erreur depuis JDOM).  Je suis depuis mon PC du boulot .... je
testerai sur un pc perso dans l'aprem pour voir, je vois que ça.

Je te tiendrai au courant.
merci en tout cas.

**Comment by ImoucheG** [comment]
Oui pas de problème :)
Ok, il y a peut être une mauvaise gestion des exceptions dans le plugin jeedom sur les retours des requêtes selon le code erreur.
Oui, tu me diras le retour si c'est un beau "200" ou autre. Dans la mesure du possible (sans le tracker GeoRide), je vais essayer de te débloquer :)

**Comment by JPI1308** [comment]
Je viens de tester depuis mon PC perso même comportement pour les requêtes
POST (togglelock, lock, unlock) => Erreur 404 à chaque fois.
Du coup je me suis remis sur mon PC de boulot, j'ai testé l'URL
https://api.georide.com/tracker/:trackerId/sonor-alarm/off en post et
c'était ok.
Donc j'en conclu que c'est ces apis qui ne fonctionnent pas pour le GR3.

**Comment by JPI1308** [comment]
Je viens de lire sur le discord, c pas compatible avec le GR3

Envoyé de mon iPhone

**Comment by ImoucheG** [comment]
Ah ... 
Je ne pourrais donc rien faire de plus malheureusement ... Désolé.

**Comment by JPI1308** [comment]
Y’a pas de mal, je t’ai surtout dérangé pour rien.

Envoyé de mon iPhone

**Comment by ImoucheG** [comment]
Non non, ça va me permettre de le préciser dans le README :)
